name: Run Scraper Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Adjust if needed

      # Optional: Install dependencies if requirements.txt exists
      - name: Install dependencies
        if: ${{ exists('requirements.txt') }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set ITEM_NAME environment variable
        run: echo "ITEM_NAME=RTX 3060" >> $GITHUB_ENV

      - name: Run scraper script
        env:
          ITEM_NAME: ${{ env.ITEM_NAME }}
        run: python scraper.py
