name: Run Scraper

on:
  push:
    branches:
      - main

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set item name
      run: echo "ITEM_NAME=RTX 3060" >> $GITHUB_ENV  # Set the ITEM_NAME environment variable

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Use the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run scraper script
      run: python scraper.py
      env:
        ITEM_NAME: ${{ secrets.ITEM_NAME }}  # Pass the environment variable to the script
